### ISSUE TITLE
what are the breaking changes?

### ISSUE THREAD

**Issue by 75lb** [koajs/static#105]
to help me safely upgrade to v4 could you write what the breaking changes from v3 are please? The API looks the same at first glance..

**Comment by coderhaoxin** [comment]
https://github.com/koajs/static/commit/d2b6dbb14b197aec2e4ef54730dbe66603ac7cc7#diff-e1bbd4f15e3b63427b4261e05b948ea8R6

broken: `async function` needs node@7.6+ :)

**Comment by 75lb** [comment]
ah, i see - thanks 👍
