### ISSUE TITLE
this module ignores errors

### ISSUE THREAD

**Issue by 75lb** [koajs/static#106]
this line leads to unreported errors and my Koa app failing silently: 
https://github.com/koajs/static/blob/master/index.js#L44

I had a bug in upstream middleware which I had no idea about, as the error (`"Can't set headers after they are sent."`) was being swallowed by the above line. 

It doesn't seem good practise to ignore errors, it reminds me of `on error resume next` in the dark days of Visual Basic. Can this be avoided?

**Comment by coderhaoxin** [comment]
e23cfcaafa0c3d8b2118892a25339b2a9e87eb01

`v4.0.1` published :)

cc @75lb thx
