### ISSUE TITLE
Path is not relative to calling file

### ISSUE THREAD

**Issue by SamHH** [koajs/static#109]
Not sure if this is intended behaviour, but it caught me out and seemed not what you'd expect.

Example tree:
```
server/
-------app.js
-------assets/
--------------humans.txt
```

And `app.js` with everything else ripped out:

```
app.use(serve('./assets'))
```

Now I would expect `GET /humans.txt` to work, but it doesn't. Instead, assuming I started node from outside the `server` dir, it would actually only work with:

```
app.use(serve('./server/assets'))
```

I'd expect that string specifying the path to be relative to the file calling it? Should I be using `__dirname` perhaps?

Tying into that, it also doesn't seem to error if a directory doesn't exist?

**Comment by jonathanong** [comment]
use an absolute path. by default, it resolves based on CWD, which is probably in the folder `server` is in
