### ISSUE TITLE
make defer default

### ISSUE THREAD

**Issue by tj** [koajs/static#11]
can't help but feel like this is a bad default, even though it matches connect

**Comment by RHavar** [comment]
Why would I want `defer` as a default?  If that was the case, I'd put it after everything else?  This seems to break the whole idea of middleware if things don't want to run in order because they might be slow

**Comment by danneu** [comment]
Now that RHavar has mentioned it, can someone clarify the intention behind `defer`?

**Comment by mikestopcontinues** [comment]
Agreed. `defer` should not be the default and its behavior is easily replicated by moving the middleware down the chain.

**Comment by coderhaoxin** [comment]
According to the conversations above, the best solution is `change nothing`?
This issue could be closed?
