### ISSUE TITLE
Not serving my public folder.

### ISSUE THREAD

**Issue by mabdullah353** [koajs/static#111]
I have tried following codes but i am unable to see static files.
```js
'use strict'

const path = require('path');
const router = require('./routes')
const Koa = require('koa')
const views = require('koa-views')
const passport = require('koa-passport')
const serve = require('koa-static')

const app = new Koa()

// Serving public assets.
app.use(serve('public'))
app.listen(8080);
```

My folder structure is that on root i have public folder.
```

public/
├── css
   └── app.css
web
├── index.js    // This contains above code. the code is complete. 

index.js  // Start script. node index.js
```

I have tried to provide all these paths in serve arguments 
```js
app.use(serve(__dirname+ '/../public'))  // resolves to valid path
app.use(serve('/<complete-absolute-path>/public')) // resolves to valid path.

app.use(serve(__dirname+ '/public')) // for testing only, path is incorrect.
app.use(serve('./public'))  // for testing only, path is incorrect.
```
Also when i added logs to check if path is resolved correctly then first two paths from above commands are valid.

but when i visit 
```
http://localhost:8080/public/css/app.css
```

It won't serve static file.

**Comment by mabdullah353** [comment]
Changing the code to following will work

```js
app.use(serve('.'))
```

**Comment by mabdullah353** [comment]
It work by the following method.

```js
// Serving public assets.
app.use(serve('.'))
```

**Comment by jonathanong** [comment]
do not use `+` to get paths. use `require('path').join()`

**Comment by KidkArolis** [comment]
+ is not the problem. I can confirm the issue happens with join as well.

**Comment by mabdullah353** [comment]
@jonathanong  i have tried both, see above in my comment there is 1  example with + sign and 1 example where i provide absolute path. both were not working.

**Comment by snollygolly** [comment]
I think the issue here is that when you do `app.use(serve('.'))`, you're serving your whole directory, so if your files are in `/public`, you make a request to `http://.../public/files` to get them.  When you use `app.use(serve('./public'))`, that same file is now served at the web root: `http://.../files`.  Another issue suggests using koa-mount to resolve this, so that's what I did:

```
const serve = require("koa-static");
const mount = require("koa-mount");
app.use(mount("/public", serve("./public")));
```

Try that and see if it works for you?

**Comment by snollygolly** [comment]
@Yugloocamai I use what I'm describing in my koa-starter kit.  Check it out and see if it works for you?

https://github.com/snollygolly/koa-starter/blob/master/index.js#L41

**Comment by shichangchun404** [comment]
const serve = require("koa-static");
const mount = require("koa-mount");
app.use(mount("/public", serve("./public")));

it works for me ,nice!

**Comment by zivyou** [comment]
@snollygolly 
Awesome analysis. It works for me. Thanks a lot

**Comment by KGKAI** [comment]
@snollygolly Why it works...

**Comment by BIT-zhaoyang** [comment]
@abdullah353 , @KGKAI , when you specify `app.use(serve('public'))`, the route will go to that folder to search. Inside visiting `http://localhost:8080/public/css/app.css, visit `http://localhost:8080/css/app.css` will do the work.
