### ISSUE TITLE
I hope koa-static would support  virtual path prefix like express-static

### ISSUE THREAD

**Issue by shuang6** [koajs/static#112]
###
Express
To create a virtual path prefix (where the path does not actually exist in the file system) for files that are served by the express.static function, specify a mount path for the static directory, as shown below:

app.use('/static', express.static('public'))
Now, you can load the files that are in the public directory from the /static path prefix.

http://localhost:3000/static/images/kitten.jpg
http://localhost:3000/static/css/style.css
###
I hope koa-static would support  virtual path prefix like express-static, so I have taken a try.
I added an option virdir(Virtual directory) to opts. Codes are following. 
`const truePath = function (ctx) {
    return (opts.virdir && !ctx.path.indexOf(opts.virdir) ?
    ctx.path.slice(opts.virdir.length) :
    ctx.path) || '/'
  }`
`try {
          done = await send(ctx, truePath(ctx), opts)
        } catch (err) {
          if (err.status !== 404) {
            throw err
          }
}`
When being using, it could be like this.
`app.use(staticServer('./static', {
  virdir: '/static'
}))`
Now it works same like express-static. But I know my skills are not enough. Maybe it has better implementations, such as regular expressions or other solutions. Anyhow, I will appreciate it if koa-static will support this function.
![qq 20170916022515](https://user-images.githubusercontent.com/24518569/30497729-81cb27c2-9a86-11e7-8066-91ee12a92311.png)

**Comment by jonathanong** [comment]
use `koa-mount`
