### ISSUE TITLE
Serve static files from a specific URL path?

### ISSUE THREAD

**Issue by shumsky** [koajs/static#113]
Hi,

If I understand correctly, koa-static always serves resources from the root URL (i.e. `/`). So, if I have a middleware:
```
const app = new Koa();
app.use(serve('./static'));
app.listen(3000);
``` 
then static files inside `./static` will be available via http://localhost:3000/path/to/file URL pattern.

But what if I need them to be available from http://localhost:3000/some-prefix/path/to/file? It seems koa-static doesn't allow to configure that. For example, in [Spring framework](https://docs.spring.io/spring-boot/docs/1.5.7.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-static-content) it is possible to do.

What do you think? Would it make sense to add such configuration option?

**Comment by pasechnik** [comment]
Hi, @shumsky 

for this purpose you can use "[koajs/mount](https://github.com/koajs/mount) Mount koa-static to a specific path"
like this:

`app.use(mount('/some-prefix', serve('./static')));`

**Comment by shumsky** [comment]
Hi @pasechnik,

Thank you. Didn't know about that module. The question is resolved.
