### ISSUE TITLE
Why do clients get a static resource for the second time without returning 304 Not Modified?

### ISSUE THREAD

**Issue by zaleGZL** [koajs/static#118]
![src](http://ox6lgrhmo.bkt.clouddn.com/src.jpg)

![network](http://ox6lgrhmo.bkt.clouddn.com/network.jpg)

**why i use express it will return 304? How should I set it to return 304 Not Modified?**

**Comment by coderhaoxin** [comment]
you need https://github.com/koajs/conditional-get
