### ISSUE TITLE
Unexpected token {

### ISSUE THREAD

**Issue by gwl002** [koajs/static#120]
![image](https://user-images.githubusercontent.com/18588945/34702326-11c6a1b8-f4e5-11e7-84d1-271047f0d278.png).I don't know why this happen.When I add the code like below myself,It worked fine.But
when i use this it show the error!
`const { resolve } = require("path")`

**Comment by TehShrike** [comment]
What version of node?

Why are you using `babel-register`?

**Comment by mbarisa** [comment]
I get same issue when using coffeescript. 

Only line added that is causing it is:
serve = require 'koa-static'

<img width="705" alt="screen shot 2018-01-29 at 5 15 49 pm" src="https://user-images.githubusercontent.com/458723/35520727-270cb89e-0518-11e8-9cb8-033c7f98400d.png">

Any ideas?

**Comment by coderhaoxin** [comment]
`koa-static@4` needs node@7.6+ :)
