### ISSUE TITLE
How to do directory listing of static folder without index file?

### ISSUE THREAD

**Issue by ashishnetworks** [koajs/static#125]
Is there a way to display a file/dir listing like apache does when you access the URL of a directory which doesn't have an index file - so it displays a listing of all that directories contents?

**Comment by adrianblynch** [comment]
@ashishnetworks - Does this do what you need?

https://github.com/koa-modules/serve-list

**Comment by ashishnetworks** [comment]
Hi, @adrianblynch thank you for the answer. Yes, I was actually expecting the package like this.
