### ISSUE TITLE
Is possible just serve only one static file instead of a folder?

### ISSUE THREAD

**Issue by renatobenks** [koajs/static#126]
Hey, I need to serve an only one static file like the example below:

```
file.json // file to be served
/src
├── api
    ├── app.js
```

I just could serve all files of the folder with the code below:

```js
app.use(serve(path.resolve(__dirname, '..', '..')));
```

However, I can't and don't wanna do it, serving all files in the folder, I just wanna serve the `file.json` as described above at path structure.

Thanks for all!

**Comment by coderhaoxin** [comment]
Try https://github.com/koajs/send 😄
