### ISSUE TITLE
Gzip has no effect.

### ISSUE THREAD

**Issue by fengshenhai-0727** [koajs/static#129]

**Comment by ceo** [comment]
same here, any solution ?

**Comment by coderhaoxin** [comment]
`koa-static`/`koa-send` only try to serve the gzipped version of a file automatically when gzip is supported by a client and if the `requested file with .gz extension exists`.

So, what you guys mean `Gzip has no effect` ?

**Comment by me7** [comment]
![image](https://user-images.githubusercontent.com/10399270/50275515-1b298700-0472-11e9-8c10-ed0681ea2d70.png)
It's mean file was sent without gzip effect (gz file is only 45kb but it's send 127kb un-gzip)
![image](https://user-images.githubusercontent.com/10399270/50275591-47dd9e80-0472-11e9-8f9d-3febcd6feb7c.png)
Look at response header also not have 'content-encoding': 'gzip'
![image](https://user-images.githubusercontent.com/10399270/50275660-7bb8c400-0472-11e9-9fe6-2f828a1284dd.png)

Here is the correct one

**Comment by stephanebachelier** [comment]
It will only send an existing gzipped version of a file. If you want to compress on the fly you should use `koa-compress`.

In other words, if you provide a file `foo.ext` and `foo.ext.gz`, the `foo.ext.gz` will be served if the `gzip` option is true and a client asks for a gzipped version.

It's a good practice to always provide a gzipped version for all text assets (js, css) and fonts except the ones already gzipped.

**Comment by budarin** [comment]
I have the same problem while having .gz and .br files
![image](https://user-images.githubusercontent.com/8055157/95024936-c7138500-068e-11eb-9550-126536d7298a.png)

and browser network info
![image](https://user-images.githubusercontent.com/8055157/95024959-e6aaad80-068e-11eb-8c6e-0a6fb21f6431.png)

server doesnt respond with gzip or brotli version
