### ISSUE TITLE
please follow semver spec

### ISSUE THREAD

**Issue by magicdawn** [koajs/static#135]
https://semver.org/

> Given a version number MAJOR.MINOR.PATCH, increment the:
> 
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

https://github.com/koajs/static/compare/4.0.3...5.0.0
version between 4.0.3 and 5.0.0 does not contain any incompatible API changes, this should be a patch version.

**Comment by coderhaoxin** [comment]
`koa-static` is a tiny wrapper of `koa-send`, just think of this change as a broken change.

https://github.com/koajs/send/pull/105

Actually, it's a bit ambivalent to determine this change as `broken` or `bug fix` :)

see also https://github.com/koajs/send/pull/82

just think of `broken` as a more safer way.
