### ISSUE TITLE
Static files not being served

### ISSUE THREAD

**Issue by ashu-vsht** [koajs/static#151]
Duplicate : Not serving my public folder. #111

Static files are not working for the release v5.0.0
I had to downgrade to 4.0.3 to make my new project work

**Comment by sdutwsl** [comment]
+1
### code:
```
const serve = require('koa-static');
const Koa = require('koa');
const mount = require("koa-mount");

const app = new Koa();

app.use(mount("/public", serve("./public")));
app.listen(3000)

console.log('listening on port 3000');

```
### folder:

```
public/
├── css
   └── app.css

server.js
```
### result
Not Found

### env
Fedora OS 32
Chrome  85.0.4183.121

**Comment by ashu-vsht** [comment]
Went back to express. 
Will try again when i have time.
