### ISSUE TITLE
context.status is always 404

### ISSUE THREAD

**Issue by ConnorDY** [koajs/static#156]
Even when `koa-static` successfully serves a file, my custom logging middleware that runs afterwards shows that `context.status` is `404`.

**Comment by Leo5878** [comment]
Is the problem urgent? I found a solution, at least why it didn't work for me

**Comment by jonathanong** [comment]
this is most likely due to the order of your middleware. make sure your logging middleware is first.

**Comment by 3imed-jaberi** [comment]
@ConnorDY, is this problem still yet ?! if yes, please can you provide a simple example to be able to help you!

**Comment by 3imed-jaberi** [comment]
@ConnorDY, I will close this issue feel free to re-open it!
