### ISSUE TITLE
duplicated URLs serving index.html

### ISSUE THREAD

**Issue by silently** [koajs/static#41]
Hello,

About html files and the fact both `http://app/` and `http://app/index.html` serve the same index.html, is there a way to prevent from serving the second route?

I guess redirecting using a router is an option, but it requires extra router processing on each request,

Thanks!

**Comment by jonathanong** [comment]
you don't want an `index.html` file to be served as `index.html`?

**Comment by silently** [comment]
no because it creates a duplicate URL and it has several disadvantages (SEO, confusion, useless ".html" file extension displayed).

**Comment by magicdawn** [comment]
https://github.com/koajs/static/blob/1.5.1/index.js#L34
the default `opt.index = index.html` makes no way to cancel or disable `index.html` serving.

Cause we pass falsy value to opt.index, it will be replaced by koa-static with `index.html` & koa-send will get `index.html` too.

This is absolute `画蛇添足` in chinese. It means `Gild the lily`, via Google Translate. :-1:

**Comment by magicdawn** [comment]
currently I'm using a option `opt.index = default.html` to disable `index.html` serving. because I don't have a default.html. This will work & koa-send will hava an unneed `fs.stat` operation. This can be avoid.

**Comment by coderhaoxin** [comment]
Maybe we can change

```js
opts.index = opts.index || 'index.html';
```

to

```js
if (opts.index !== false) opts.index = opts.index || 'index.html';
```

and also fix the logic in `koa-send` (when `format` is `true`)

**Comment by magicdawn** [comment]
> 
```
if (opts.index !== false) opts.index = opts.index || 'index.html';
```
and also fix the logic in koa-send (when format is true)


Pretty good. :+1:

**Comment by danneu** [comment]
@silently has a good point - when you want `GET / ` to serve `public/index.html`, then you'd seldom want to also serve `GET /index.html` anymore.

Naive fix would be to yield next if `opt.index && this.path.endsWith('/' + opt.index)`.
