### ISSUE TITLE
allow overriding maxage per path

### ISSUE THREAD

**Issue by emertechie** [koajs/static#49]
I'm serving up an Angular app and I want to heavily cache my static assets but have no cache on my index.html page.

At the moment the maxage setting applies to all files in the served directory.

I needed this for myself so I've forked the project and will issue a pull request shortly

**Comment by jonathanong** [comment]
we can have a `.staticCacheControl=` property that overrides the options or something if you set it in the route

**Comment by emertechie** [comment]
Yea I'm not happy with the API I came up with in the PR and I've since moved to hosting my Angular app on S3/CloudFront anyway.

But for an API, maybe something like this would be better:

```js
app.use(serve(__dirname + '/assets'), {
    overrides: {
        'index.html': { maxage: foo },
        'components/*.html': { maxage: bar }
    }
});
```

But, like @coderhaoxin mentioned in the PR notes, you could also just serve the 'index.html' etc files first using [koajs/sendfile ](https://github.com/koajs/sendfile) and then have everything else fall back to this middleware. That's probably the easiest. So will close this for now

**Comment by armellarcier** [comment]
Here is the workaround I'm using FWIW

```javascript
app.use(serve('./public', {
    maxage: 1000 * 60 * 60 * 24,// 1d,
    setHeaders: (res, path, stats) => {
        if(path && (
            path.endsWith('.html')
        )) {
            res.setHeader('Cache-Control', 'max-age=0');
        }
    }
}));
```

This way, html files are not cached.
