### ISSUE TITLE
v1.4.x → 1.5.0 breaking change due to defaulting opts.format to true

### ISSUE THREAD

**Issue by danneu** [koajs/static#53]
https://github.com/koajs/static/commit/0e70310b0e35b559e3f50b0c6aa3de646eae409e introduces a breaking change by defaulting `opts.format = true` which introduces koa-send's new v2.0.0 behavior which can be seen in the highlighted lines in this diff: https://github.com/koajs/send/commit/bfd4cbcb9e51ff5f40ad786a26a32e17140efd2a#diff-168726dbe96b3ce427e7fedce31bb0bcR70

I recommend removing that `opts.format = true` defaulting behavior and republishing the minor version.

Illustration:

    app.use(require('koa-static')('public'));
    app.use(route.get('/', function*() {
      this.body = 'hello world';
    }));

- In v1.4.x, `GET /` will render `hello world` since `/` is a directory and just short-circuits with 404.
- In v1.5.0, `GET /` will attempt to serve `public/index.html` and 404 if it doesn't exist. The `/` route cannot be accessed.

**Comment by jonathanong** [comment]
wanna make a PR?

**Comment by coderhaoxin** [comment]
@danneu reopen if the broken still exists

**Comment by danneu** [comment]
Looks good, thanks.
