### ISSUE TITLE
if i want to use full path, what should i do?

### ISSUE THREAD

**Issue by node-rookie** [koajs/static#54]
use ../public/index.js , not ../index.js

**Comment by ivan-kleshnin** [comment]
@node-rookie I also hit this...

Use https://github.com/koajs/static-cache with a `prefix` option
```js
serve(__dirname + '/public', {prefix: "/public/"})
```

**Comment by coderhaoxin** [comment]
try https://github.com/koajs/mount

**Comment by ivan-kleshnin** [comment]
@coderhaoxin thanks for the hint!
