### ISSUE TITLE
Specify a default 404 file

### ISSUE THREAD

**Issue by silenceisgolden** [koajs/static#64]
Can we get an option to set a 404 file for requests that 404? It can definitely default to `false`, but if set to a file path then serve that file path in the body. This would be especially helpful for almost static sites being run by koa and koa middleware.

**Comment by tj** [comment]
HmMmm, personally I'd say a 404 is more of a site-wide trait than a static file serving trait, maybe we just need a tiny `app.use(notfound(path))`

**Comment by silenceisgolden** [comment]
Ok, I'll whip that up then. Thanks!

**Comment by mashhoodr** [comment]
@silenceisgolden can you please share the middleware you wrote for this, did you use koa-send to manually send serve the files on 404?

**Comment by cdaringe** [comment]
i'd like to see this too. @mashhoodr, what did you impl look like?

**Comment by michielbdejong** [comment]
FWIW, not sure if this is the best answer, but I got this working with:

```js
const Koa = require("koa");
const koaSend = require("koa-send");
const koaStatic = require("koa-static");

const app = new Koa();
app.use(koaStatic("./public/", {}));
app.use(async ctx => {
  if (ctx.status === 404) {
    await koaSend(ctx, "index.html", { root: "./public/" });
  }
});
app.listen(3000);
```
