### ISSUE TITLE
Serving name.html files under /name as well as /name.html ?

### ISSUE THREAD

**Issue by 01AutoMonkey** [koajs/static#65]
Any plans to support serving static html files on their "basename path"? That is for example [http-server](https://github.com/indexzero/http-server), github pages, and others, serve .html files both under `/name.html` and `/name` by default, so the index page would be accessible at:
- `/`
- `/index`
- `/index.html`

And a non-index page at:
- `/page`
- `/page.html`

For me specifically I need to save my html files with an .html extension, serve them as simply as possible (static folder serve), and view them through an URL without the .html extension (since it's cleaner and a common pattern for wikis).

**Comment by ilikebits** [comment]
:+1: This would be super convenient; even better would be replicating the `extensions` option behaviour from https://github.com/expressjs/serve-static.

**Comment by coderhaoxin** [comment]
I'm +1 for this, need add support in [koajs/send](https://github.com/koajs/send) IMO, cc @jonathanong

**Comment by tj** [comment]
duplicate content? maybe as an option, but this will be bad for SEO as a default

**Comment by coderhaoxin** [comment]
> maybe as an option

Yes, expressjs/serve-static supports this by option `extensions`, defult `false`.

**Comment by medoix** [comment]
+1

**Comment by Necromos** [comment]
I added this functionality to koa-send https://github.com/koajs/send/pull/65 
Lets hope that admins will add it :)

**Comment by nicluo** [comment]
I'm using koa v2, koa-static v3, koa-mount v2, it just works right out of the box. :)

`app.use(mount('/public', serve('public', {extensions: ['.html']})));`
