### ISSUE TITLE
Difference with koa-send

### ISSUE THREAD

**Issue by pensierinmusica** [koajs/static#67]
Hi,

Sorry for the silly question, I'm trying to figure out... what is the difference between `koa-static` and [`koa-send`](https://github.com/koajs/send)?

The two packages seem to be very similar, and I'm getting confused about which one to use.

Thanks!

**Comment by coderhaoxin** [comment]
koa-static is a tiny wrapper of koa-send, to be used as a `koa middleware` directly.
But you can use `koa-send` for some scenarios that need more self logic. Such as https://github.com/koajs/static/pull/48

**Comment by pensierinmusica** [comment]
I see, thanks! Sounds like a useful little piece of information, just for clarity and simplicity. I'll create a PR to include it in readme. Cheers!
