### ISSUE TITLE
koa@next?

### ISSUE THREAD

**Issue by niftylettuce** [koajs/static#71]
use `async` and `await` instead?

**Comment by coderhaoxin** [comment]
For now, you can try `koa-convert`

more migration process info, https://github.com/koajs/koa/issues/625

**Comment by tejasmanohar** [comment]
use [koa-convert](https://www.npmjs.com/package/koa-convert). if that doesn't work, we'll consider supporting koa v2, but we've decided not to use babel in this org. once async/await is native, we'll use it.

**Comment by tejasmanohar** [comment]
lol @coderhaoxin tied me :P

**Comment by coderhaoxin** [comment]
:cry:

**Comment by tejasmanohar** [comment]
;)
