### ISSUE TITLE
.mp4 video unable to play in Safari

### ISSUE THREAD

**Issue by Alexorz** [koajs/static#75]
Hello,

I got an error when I open a .mp4 file in browser which is hosted by koa-static, here is the message in terminal:
````
Error: write EPIPE
      at exports._errnoException (util.js:746:11)
      at WriteWrap.afterWrite (net.js:775:14)
````

Chrome can play the video, but Safari cannot play it,
and when I open the video in either Chrome or Safari, the error always appears.

Env:
* `nodeJs` v0.12.4
* `koa` v0.21.0
* `koa-static` v1.4.9

**Comment by coderhaoxin** [comment]
I don't think it's a good idea to serve video files by koa-static.

For your use case, I think `content range` support is required, such as [yorkie/koa-range](https://github.com/yorkie/koa-range).

**Comment by tejasmanohar** [comment]
we should try to get koa-range here in koajs/* org / cc @jonathanong

**Comment by jonathanong** [comment]
@yorkie https://github.com/yorkie/koa-range/issues/6

**Comment by jonathanong** [comment]
yeah video files should be hosted by s3 or at least behind a CDN that handles range requests

**Comment by jonathanong** [comment]
it's in the org now!

**Comment by tejasmanohar** [comment]
yay, can prob close this issue

**Comment by Alexorz** [comment]
Got that, thanks all of you :)
