### ISSUE TITLE
Can I use koa-static to serve individual files instead of directories? (e.x. serve assets folder on /assets and an config.toml file that's not in a served directory at /config.toml )

### ISSUE THREAD

**Issue by 01AutoMonkey** [koajs/static#76]
I can serve directories alright:

```node
app.use(serve(pub_path));
```

But I'm at loss to figure out how to serve individual files.

Can I do this with koa-static? Or is there perhaps some simple way to do that with plain koa?

I guess I could do something like:

```node
app.use(function *(){
  this.body = 'Hello World';
});
```

And replace `'Hello World'` with the content of config.toml, but I'd rather use koa-static if possible.

**Comment by coderhaoxin** [comment]
try
https://github.com/koajs/sendfile
https://github.com/koajs/send
