### ISSUE TITLE
fails on node v5.7.0

### ISSUE THREAD

**Issue by amitport** [koajs/static#77]
Until reverting to node `node v5.6.0`, I kept getting 'malicious path' error on `node v5.7.0` 

(this is probably a node issue, but someone needs to debug koa/koa-send/koa-static to figure out where it is)

**Comment by coderhaoxin** [comment]
Maybe [node 5.7.1](https://github.com/nodejs/node/issues/5400) will fix this!

**Comment by syuilo** [comment]
I have the same issue.

**Comment by tejasmanohar** [comment]
https://github.com/nodejs/node/issues/5393 maybe due to this - haven't checked it out

**Comment by Goatic** [comment]
I'm getting the same error - any workarounds?

**Comment by vzaidman** [comment]
I'm getting the same error as well- any workarounds?

**Comment by coderhaoxin** [comment]
Anyone can checkout this on win with node@5.7.1?

**Comment by amitport** [comment]
:+1:  works for me, closing this
