### ISSUE TITLE
The request of static file is blocked on Node.JS 5.7.1

### ISSUE THREAD

**Issue by XuJinNet** [koajs/static#78]
Update to Node.JS 5.7.1，The every request of static file is blocked, not have response to browser.
koa 1.1.2,  koa-static 1.5.2, OS: Windows 10 64bit

`app.use(koaStatic(path.join(__dirname, '..', 'client')));`

**Comment by coderhaoxin** [comment]
tests passed with node@5.7.1 (osx), what's your platform?

**Comment by XuJinNet** [comment]
Every request for static file is blocked，not have response.
My OS: Windows 10 64bit

**Comment by tejasmanohar** [comment]
runnable example? also, expand on "is blocked"?

**Comment by XuJinNet** [comment]
`app.use(koaStatic(path.join(__dirname, '..', 'client')));`

![1](https://cloud.githubusercontent.com/assets/442382/13485196/1f05981c-e140-11e5-9c89-79023253329a.png)
![2](https://cloud.githubusercontent.com/assets/442382/13485199/2358de7e-e140-11e5-8de9-76fa63b883cf.png)

**Comment by XuJinNet** [comment]
Maybe my os environment have problem.
