### ISSUE TITLE
Add a v2.x or next branch

### ISSUE THREAD

**Issue by PlasmaPower** [koajs/static#79]
It shouldn't be too hard to convert the existing code to Koa v2. Unless we are implementing #72 soon, I think it would be a good idea to convert the existing code to v2 given that the switch to v2 may come sooner than expected. If nobody wants to convert the code, I can do it, but I can't create the branch, only a PR to an existing branch.

**Comment by coderhaoxin** [comment]
Yea!

**Comment by coderhaoxin** [comment]
https://github.com/koajs/static/tree/next

**Comment by coderhaoxin** [comment]
```
latest: 2.0.0
next: 3.0.0
```
