### ISSUE TITLE
Can't access URL with dot

### ISSUE THREAD

**Issue by skrobek** [koajs/static#82]
Hey, I'm using koa as my dev server and static to serve generated files. In application, I have routes which contain `.` in the slug value, for instance: `/something/ng.lsp`. I'm wondering why I got 404 here ?

**Comment by JuHwon** [comment]
same here. id like to serve for my dev environment a `/.tmp` path though i also get a 404.

**Comment by coderhaoxin** [comment]
@JuHwon set opts `{hidden: true}`, see https://github.com/koajs/send, `koa-static` deps `koa-send`.

**Comment by coderhaoxin** [comment]
@skrobek try `DEBUG=koa-send node your-server.js` or `DEBUG=koa-* node your-server.js` to print some debug msgs?

**Comment by JuHwon** [comment]
sadly setting the hidden flag does not work.
i am doing `app.use(convert(serve(path.join(rootDir, './.tmp'), { hidden: true })));` when i only write `'./tmp'` it works. though both folders exist and are the same.

While debugging i had the following output:
```
  koa-send send "/.tmp/templates.js" {"root":"/home/account/Projects/myproj/src/client","index":"index.html"} +43ms
  koa-send send "/.tmp/templates.js" {"root":"/home/account/Projects/myproj","index":"index.html"} +0ms
  koa-send send "/.tmp/templates.js" {"hidden":true,"root":"/home/account/Projects/myproj/.tmp","index":"index.html"} +0ms
```

**Comment by skrobek** [comment]
@coderhaoxin `koa-send send "/stock/ng.l" {"hidden":true,"root":"/Users/skrobek/DEV/projects/stockflare/snow/src/static","index":"index.html"} +14s`

**Comment by JuHwon** [comment]
oh i just noticed when i am serving `/.tmp` already i should not access via `/.tmp/requested.file`.
I just have to request the `requested.file` without the served path.
