### ISSUE TITLE
Malicious Path

### ISSUE THREAD

**Issue by liuhong1happy** [koajs/static#84]
when I use `koa-static` 2.0.0 in windows, the render page's content is `Malicious Path`.

**Comment by tejasmanohar** [comment]
i don't use windows, but a small, runnable example would be nice for those who do

**Comment by kaaann** [comment]
koa-static": "^3.0.0"

app.use(serve(__dirname+'/public'));

when I use koa-static 3.0.0 in windows 7, the render page's content is Malicious Path.

**Comment by kaaann** [comment]
koa-static": "^3.0.0"
modify：
return send(ctx, ctx.path.slice(1), opts)
Win7 it is OK.

**Comment by kaaann** [comment]
reson:
window7,node.js v5.7.0
path.parse("/a.txt");
{ root: '', dir: '', base: 'a.txt', ext: '.txt', name: 'a' }

window7,node.js v6.6.0
path.parse("/a.txt");
{ root: '/', dir: '/', base: 'a.txt', ext: '.txt', name: 'a' }

 Reference: https://github.com/nodejs/node/pull/8293
#https://github.com/nodejs/node/pull/8293

Please upgrade node.js
