### ISSUE TITLE
v2.0.0 throw koa deprecated warning

### ISSUE THREAD

**Issue by AndreLion** [koajs/static#86]
`koa-static 2.0.0` requires `koa-send 3.1.1`, which throws a deprecated warning:

koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x

Which means `koa-static 2.0.0` does NOT fully support `koa 2`

**Comment by hiwanz** [comment]
@AndreLion 

Use `koa-static 3.0.0` instead of `koa-static 2.0.0` with the command:

```sh
npm install koa-static@next
```

**Comment by AndreLion** [comment]
Thanks for your advice and fast feedback.
closing it.
