### ISSUE TITLE
koa-static not found on index.html

### ISSUE THREAD

**Issue by PrimeLens** [koajs/static#94]
Not sure why this is not working. I've uploaded the simplest server here
https://github.com/PrimeLens/koa-why-does-this-give-not-found

**Comment by coderhaoxin** [comment]
@PrimeLens 

```js
app.use(require('koa-static')(__dirname + '/public'))
```

not

```js
app.use(require('koa-static')(__dirname + 'public'))
```

**Comment by PrimeLens** [comment]
Thanks!

**Comment by PrimeLens** [comment]
Can't believe I missed something so obvious. Thats embarrassing and stupid of me. Its the little things you sometimes miss
