### ISSUE TITLE
Specific header for static files

### ISSUE THREAD

**Issue by zauker** [koajs/static#95]
Hi, I have a question, is possible to set a specific header for static files served by koa-static?
I need for example add a **X-Frame-Option** for my document located into `/public/document`

Michele

**Comment by coderhaoxin** [comment]
@zauker you can use `setHeaders` option. See https://github.com/koajs/send#setheaders

😢 I'll add this option to readme

**Comment by zauker** [comment]
So I need to something like this?

```
var app = koa(),
    serve = require('koa-static');

app.use(serve('app/public', {setHeaders: myfunction()}));

```

**Comment by IlyaSemenov** [comment]
Example:

```js
app.use(mount('/media', serve(path.resolve(config.app.root, 'var/media'), {
  setHeaders (res) {
    res.setHeader('cache-control', 'immutable')
  },
})))
```

**Comment by benstevens48** [comment]
Is it possible to document this in the list of options so that it's officially supported? I've installed the typescript definitions for koa-static but this option is not included (presumably because it's not officially documented).
