### ISSUE TITLE
koa deprecated

### ISSUE THREAD

**Issue by AndrewTi** [koajs/static#97]
koa deprecated Support for generators will be removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x---deprecate

how fix it?

**Comment by coderhaoxin** [comment]
@AndrewTi 

The latest version on npm is now `v3.0.0`, this version should work with `koa@2`.
I also switch branch `next` to `master` :)
